# Generated by Django 4.0.4 on 2022-05-27 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='workspace_permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creator', models.BooleanField(default=True)),
                ('permission_add_board', models.BooleanField(default=True)),
                ('permission_add_file', models.BooleanField(default=True)),
                ('permission_add_user', models.BooleanField(default=True)),
                ('permission_change_workspace', models.BooleanField(default=True)),
                ('permission_delete_workspace', models.BooleanField(default=True)),
                ('permission_delete_user', models.BooleanField(default=True)),
                ('permission_read_boards', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
                ('workspace_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='workspace_users',
            field=models.ManyToManyField(related_name='w_usrs', through='home.workspace_permissions', to='home.user'),
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('state', models.IntegerField()),
                ('order', models.IntegerField()),
                ('file', models.FileField(null=True, upload_to='')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.board')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='board_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='board_files/')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='home.board')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='workspace_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.workspace'),
        ),
    ]
